triggers:
- envs: []
  last_enabled_at: 2024-04-13 22:20:26.031594+00:00
  name: Training set v0
  pipeline_uuid: prepare_data
  schedule_interval: '@daily'
  schedule_type: time
  settings:
    landing_time_enabled: true
  sla: null
  start_time: 2023-06-26 00:00:00+00:00
  status: active
  variables: {}
